sudo: required
services:
    - docker

before_install:
    - docker build -t carlosfn224/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true carlosfn224/react-test npm test

after_success:
    - docker build -t carlosfn224/multi-client ./client
    - docker build -t carlosfn224/multi-nginx ./nginx
    - docker build -t carlosfn224/multi-server ./server
    - docker build -t carlosfn224/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Takes these images and push them to docker hub
    - docker push carlosfn224/multi-client
    - docker push carlosfn224/multi-nginx
    - docker push carlosfn224/multi-server
    - docker push carlosfn224/multi-worker
    

